### ISSUE TITLE
Export track colors

### ISSUE THREAD

**Issue by melitele** [furkot/furkot-gpx#10]
Include the "color code" in the GPX Track Export file as Garmin Extensions: i.e,

	<trk>
		<name>Hard</name>
		<gpxtrx:TrackExtension>
			<gpxtrx: DisplayColor>Red</gpxtrx: DisplayColor>
		</gpxtrx:TrackExtension>
	</trk>

**Comment by allthingssatnav** [comment]
For Garmin GPX...
![screen shot 2015-06-20 at 23 05 28](https://cloud.githubusercontent.com/assets/11207242/8270673/f26a4a5a-17a0-11e5-8cee-fbbee5ab195c.png)

**Comment by melitele** [comment]
Two questions:

1. Should the route color option selected for the display in Furkot affect the colors in the exported GPX file or should we only distinguish between locked and unlocked routes?

2. Should we use colors as closely matching Furkot's (see below) as possible or use different colors in the exported GPX file?

The closest match of route colors in Furkot to Garmin colors as defined in the GxpExtensions schema http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd is as follows:

normal (unlocked) - Blue
preserved (locked) - Dark Magenta
odd day - Blue
even day - Magenta
outbound leg - Blue
inbound (return) leg - Cyan

**Comment by allthingssatnav** [comment]
Color is a personal selection based upon the reason for differentiation: as is eluded to in the XML example:

`<trk>
    <name>Hard</name>
    <gpxtrx:TrackExtension>
        <gpxtrx: DisplayColor>Red</gpxtrx: DisplayColor>
    </gpxtrx:TrackExtension>
</trk>`

Typically, on GPS devices, high-contrast colors are chosen for differentiation. 
The current route color options in Furkot are very good options for differentiating Furkot route conditions but do not address User reasons for differentiation. The User should choose/set the Color for the Exported Track/Route.
If (1) then it would be appropriate to offer most of the Garmin Color Options to the User.

**Comment by melitele** [comment]
Until we implement an option to select different color for each route  in Furkot, the best we can do is to map colors Furkot uses to Garmin colors based on route type and display preferences (locked/unlocked, alternate days, inbound/outbound).

If that's not useful, we'll defer this issue until the selecting color per route is implemented.

**Comment by allthingssatnav** [comment]
I think the color in Furkot is of value to many, especially on the more complex Trips: I know I appreciate it. I don't think extending this coloration to the device is as valuable as being able to select color for User purposes. I would suggest deferring until such time as that feature can be implemented.

**Comment by melitele** [comment]
done
