### ISSUE TITLE
Garmin GPX Export <Transportation Mode>

### ISSUE THREAD

**Issue by drtbyk** [furkot/furkot-gpx#11]
Furkot Exports Garmin GPX and sets the Route 'Transportation Mode' to Automotive regardless of the route-type selected in Furkot (example below).
<img width="450" alt="screen shot 2016-06-25 at 07 18 11" src="https://cloud.githubusercontent.com/assets/8745955/16357229/1589a68e-3aa5-11e6-9c4c-ba0ce41cf0cd.png">

It would be advantageous for Garmin folks if the TransportationMode for the Route <rte> was set to the equivalent Furkot route-type used as the overall route-type for the PLAN Day - not just Automotive.  

I realize the Furkot routes can have segments of various route-types in a Day and so can a Garmin GPX route (example follows).
<img width="497" alt="screen shot 2016-06-25 at 07 18 25" src="https://cloud.githubusercontent.com/assets/8745955/16357232/1c536d2e-3aa5-11e6-8fd8-8e5210542bb9.png">

The Garmin Transportation Modes relative to Furkot are:
Automotive
Motorcycling
Hiking
Bicycling
Direct = Furkot OTHER
Thank you for your consideration.

**Comment by melitele** [comment]
Release 2.0.7:
- fixes route TransportationMode to reflect the travel mode set for the route
- adds ViaPointTransportationMode to every route point of the route containing segments with travel mode different than the overall route travel mode
