### ISSUE TITLE
Garmin GPX Route Export

### ISSUE THREAD

**Issue by allthingssatnav** [furkot/furkot-gpx#3]
Is adding a Route <rte> for the final Day when there is no route for that Day. This only happens when Garmin GPX and Routes is selected (appended Points have no effect).

**Comment by allthingssatnav** [comment]
In the latest build that supports Garmin Routes and the selection of Routes + Points and Tracks, when Routes and/or Tracks are selected, the output GPX file still produces an empty Route and/or Track on the last Day of a Trip when the last Day is a multi-day layover Stop which has no route.

**Comment by allthingssatnav** [comment]
Sorry, inadvertently closed.

**Comment by allthingssatnav** [comment]
Garmin GPX Routes Export appears to be working very well.

**Comment by melitele** [comment]
fixed - empty routes/tracks are discarded before the data is passed to this module

**Comment by allthingssatnav** [comment]
The Furkot Garmin GPX Routes Export is placing an additional Subclass element just before closing the RoutePointExtension for both ViaPoint (STOP) and ShapingPoint (Pass-through). This causes issues with the route in some devices where ShapingPoints are not always read properly. This additional Subclass element should not be added.
Example:
     
![screen shot 2015-06-20 at 10 10 11](https://cloud.githubusercontent.com/assets/11207242/8268276/9b7fd262-1734-11e5-894d-6953b2ef350f.png)



I missed this in my initial testing as the route I was using was to simple.
