### ISSUE TITLE
Swap Furkot Comment and Description data in GPX & Garmin GPX Export files.

### ISSUE THREAD

**Issue by allthingssatnav** [furkot/furkot-gpx#5]
Garmin has decided to only include GPX <cmt> comment information for Waypoints in their newer GPS devices. Even though this is inconsistent with GPX Schema since <desc> is defined as for User Information purposes not the GPS device.  They still include a merged Comment-Description field for User Custom POI data - as they always have. I confirmed this with Garmin Software Engineering. 

It would therefore be preferable to have Furkot Export Stops (waypoints) Description text as GPX Comments <cmt> and the Address field data as GPX Descriptions <desc>.

**Comment by melitele** [comment]
I think we want to treat  Garmin route GPX export (1) and generic GPX export (2) separately for this issue.

1. With Garmin route GPX we already export addresses as Address Waypoint Extension as defined in this schema: http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd . Presumably Garmin devices that support ViaPoint/ShapingPoint Route Extension also support Address Waypoint Extension. If that's the case I propose we export stop description text as <cmt> element. Given your discussion with Garmin SE I don't see much value in exporting <desc> element at all.

2. When exporting a generic  GPX file I prefer merging to swapping. If a stop has both address and description corresponding <wpt> element will have both <cmt> and <desc> set to the same value: address followed by the description.

**Comment by allthingssatnav** [comment]
A perfect solution.

**Comment by melitele** [comment]
done
