### ISSUE TITLE
Superfluous Subclass element

### ISSUE THREAD

**Issue by melitele** [furkot/furkot-gpx#8]
The Furkot Garmin GPX Routes Export is placing an additional Subclass element just before closing the RoutePointExtension for both ViaPoint (STOP) and ShapingPoint (Pass-through). This causes issues with the route in some devices where ShapingPoints are not always read properly. This additional Subclass element should not be added.
Example:
![9b7fd262-1734-11e5-894d-6953b2ef350f](https://cloud.githubusercontent.com/assets/77260/8268315/49b25aca-174f-11e5-8f1c-fdf817682d11.png)

**Comment by melitele** [comment]
According to the Garmin extension schema - http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd - the Subclass element is a correct subelement of both RoutePointExtension and rpt elements. If it is causing problems in some devices it may be because its value is not correct. Sadly, acceptable values of Subclass elements are not defined in the above schema.

**Comment by allthingssatnav** [comment]
Garmin generates these Subclass codes based upon their proprietary GDB routing algorithm and associated map routing data. There is no documentation for this. I recommend the removal of the RoutePointExtension element until further reverse engineering can take place or Garmin provides a "generic" Subclass code that will work for their devices.

**Comment by melitele** [comment]
Removing entire RoutingPointExtension element will also remove all its `<gpxx:rtp>` subelements that represent Furkot Track Points between Stops. According to the Garmin extension schema - http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd - the Subclass element is optional (both on RoutePointExtension and `<gpxx:rtp>`  level). Would it be enough to remove Subclass element but leave  `<gpxx:rtp>` subelements?

**Comment by allthingssatnav** [comment]
When RoutePointExtension is used without a proper Subclass it only causes problems on newer devices that use the Trip Planner Extensions.  The RoutePointExtension path data basically conflicts with the routing engine's use of the ViaPoint and ShapingPoint locations. I have confirmed this on multiple devices and with several Routes. Best to just drop the RoutePointExtension.

**Comment by melitele** [comment]
Removed RoutePointExtension elements. When we obtain valid codes for Subclass elements, we can emit RoutePointExtension elements again.
